#!/usr/bin/env bash
# =====================================================================
#  Nexus Bot Hosting - Linux bot node installer
#
#  Turns this Linux machine into the "bot node": it stores every bot's
#  files, runs the bots in Docker, and serves per-bot SFTP. The website
#  (panel) keeps running on the Windows machine and connects here.
#
#  Usage (from the cloned repo):
#      sudo bash installer/linux/install-node.sh
#
#  Optional environment overrides:
#      PANEL_IP=1.2.3.4   only allow the panel's IP to reach the node API port
#      AGENT_PORT=8443    node API port (panel -> node)
#      SFTP_PORT=2222     SFTP port (users -> node)
#
#  Safe to re-run (e.g. after `git pull`): the token and TLS certificate are
#  kept, so the panel's settings stay valid.
# =====================================================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this as root:  sudo bash $0"
  exit 1
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SERVER_DIR="$REPO_DIR/server"
CONF_DIR=/etc/nexus-node
ENV_FILE="$CONF_DIR/node.env"
DATA_ROOT=/var/lib/nexus
SERVICE=nexus-node
AGENT_PORT="${AGENT_PORT:-8443}"
SFTP_PORT="${SFTP_PORT:-2222}"
PANEL_IP="${PANEL_IP:-}"

step() { echo; echo "==> $*"; }

if [ ! -f "$SERVER_DIR/src/botnode/agent.js" ]; then
  echo "Can't find $SERVER_DIR/src/botnode/agent.js - run this from inside the cloned repo."
  exit 1
fi

# ---------------------------------------------------------------------
step "[1/8] Installing base packages"
if command -v apt-get >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y curl ca-certificates openssl git build-essential python3
  PKG=apt
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y curl ca-certificates openssl git gcc-c++ make python3
  PKG=rpm
elif command -v yum >/dev/null 2>&1; then
  yum install -y curl ca-certificates openssl git gcc-c++ make python3
  PKG=rpm
else
  echo "Unsupported distro (need apt, dnf or yum). Use Ubuntu/Debian/RHEL/Rocky/Alma/Fedora."
  exit 1
fi

# ---------------------------------------------------------------------
step "[2/8] Docker"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker
docker version --format 'Docker {{.Server.Version}}'

# ---------------------------------------------------------------------
step "[3/8] Node.js (20+)"
NODE_MAJOR=0
if command -v node >/dev/null 2>&1; then
  NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
fi
if [ "$NODE_MAJOR" -lt 20 ]; then
  if [ "$PKG" = apt ]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
  else
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    (dnf install -y nodejs || yum install -y nodejs)
  fi
fi
NODE_BIN="$(command -v node)"
echo "Node $("$NODE_BIN" -v) at $NODE_BIN"

# ---------------------------------------------------------------------
step "[4/8] Installing server dependencies"
cd "$SERVER_DIR"
npm ci --omit=dev --no-fund --no-audit

# ---------------------------------------------------------------------
step "[5/8] Token, TLS certificate and config"
mkdir -p "$CONF_DIR" "$DATA_ROOT/bots" "$DATA_ROOT/data"
chmod 700 "$CONF_DIR"

AGENT_TOKEN=""
if [ -f "$ENV_FILE" ]; then
  AGENT_TOKEN="$(grep -E '^AGENT_TOKEN=' "$ENV_FILE" | cut -d= -f2- || true)"
fi
if [ -z "$AGENT_TOKEN" ]; then
  AGENT_TOKEN="$(openssl rand -hex 32)"
fi

if [ ! -f "$CONF_DIR/node.crt" ] || [ ! -f "$CONF_DIR/node.key" ]; then
  openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes \
    -days 3650 -subj "/CN=nexus-bot-node" \
    -keyout "$CONF_DIR/node.key" -out "$CONF_DIR/node.crt" 2>/dev/null
  chmod 600 "$CONF_DIR/node.key"
fi

cat > "$ENV_FILE" <<EOF
# Nexus bot node - generated by install-node.sh
AGENT_PORT=$AGENT_PORT
AGENT_TOKEN=$AGENT_TOKEN
AGENT_TLS_CERT=$CONF_DIR/node.crt
AGENT_TLS_KEY=$CONF_DIR/node.key
BOTS_DIR=$DATA_ROOT/bots
DATA_DIR=$DATA_ROOT/data
DOCKER_SOCKET=/var/run/docker.sock
SFTP_PORT=$SFTP_PORT
MAX_UPLOAD_SIZE_MB=200
EOF
chmod 600 "$ENV_FILE"

# ---------------------------------------------------------------------
step "[6/8] systemd service ($SERVICE)"
cat > /etc/systemd/system/$SERVICE.service <<EOF
[Unit]
Description=Nexus Bot Hosting - bot node (files, Docker, SFTP)
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=simple
WorkingDirectory=$SERVER_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$NODE_BIN $SERVER_DIR/src/botnode/agent.js
Restart=always
RestartSec=3
User=root

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable $SERVICE >/dev/null
systemctl restart $SERVICE

# ---------------------------------------------------------------------
step "[7/8] Firewall"
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  ufw allow "$SFTP_PORT"/tcp
  if [ -n "$PANEL_IP" ]; then
    ufw allow from "$PANEL_IP" to any port "$AGENT_PORT" proto tcp
  else
    ufw allow "$AGENT_PORT"/tcp
  fi
  echo "ufw rules added."
elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
  firewall-cmd --permanent --add-port="$SFTP_PORT"/tcp
  if [ -n "$PANEL_IP" ]; then
    firewall-cmd --permanent --add-rich-rule="rule family=ipv4 source address=$PANEL_IP port port=$AGENT_PORT protocol=tcp accept"
  else
    firewall-cmd --permanent --add-port="$AGENT_PORT"/tcp
  fi
  firewall-cmd --reload
  echo "firewalld rules added."
else
  echo "No active ufw/firewalld found - make sure TCP $AGENT_PORT and $SFTP_PORT are open"
  echo "(including in your cloud provider's security group / firewall panel)."
fi

# ---------------------------------------------------------------------
step "[8/8] Pre-pulling bot runtime images"
docker pull python:3.12-slim
docker pull node:20-slim

# ---------------------------------------------------------------------
PUBLIC_IP="$(curl -fsS --max-time 5 https://ifconfig.me 2>/dev/null || true)"
if [ -z "$PUBLIC_IP" ]; then
  PUBLIC_IP="$(hostname -I | awk '{print $1}')"
fi
CA_B64="$(base64 -w0 "$CONF_DIR/node.crt")"

sleep 2
if systemctl is-active --quiet $SERVICE; then
  STATUS="running"
else
  STATUS="NOT RUNNING - check: journalctl -u $SERVICE -n 50"
fi

SETTINGS="$CONF_DIR/panel-settings.txt"
cat > "$SETTINGS" <<EOF
BOT_NODE_URL=https://$PUBLIC_IP:$AGENT_PORT
BOT_NODE_TOKEN=$AGENT_TOKEN
BOT_NODE_CA=$CA_B64
SFTP_HOST=$PUBLIC_IP
SFTP_PORT=$SFTP_PORT
EOF
chmod 600 "$SETTINGS"

cat <<EOF

=====================================================================
 Bot node installed. Service: $SERVICE ($STATUS)

 On the WINDOWS panel machine, put these lines in server\\.env
 (replace any existing SFTP_HOST / SFTP_PORT lines), then run:
     installer\\nssm\\nssm.exe restart NexusBotHosting

$(cat "$SETTINGS")

 (Saved to $SETTINGS - view again with: sudo cat $SETTINGS)
 If $PUBLIC_IP is not the address the Windows machine should use
 (e.g. both are on a private network), change BOT_NODE_URL's host.

 Logs:     journalctl -u $SERVICE -f
 Update:   cd $REPO_DIR && git pull && sudo bash installer/linux/install-node.sh
 Bot files live in $DATA_ROOT/bots
=====================================================================
EOF
